version: "3"

services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - nginx
      - httpd
    networks:
      - kadai-ouyou-net
    volumes:
      - ./logs/proxy:/var/log/nginx

  nginx:
    build: ./nginx
    networks:
      - kadai-ouyou-net
    volumes:
      - ./logs/nginx:/var/log/nginx

  httpd:
    build: ./httpd
    networks:
      - kadai-ouyou-net
    volumes:
      - ./logs/httpd:/usr/local/apache2/logs

networks:
  kadai-ouyou-net:
    driver: bridge
