server {
    listen 80;
    server_name localhost;

    # /web1/ へのアクセスを nginx コンテナへ転送
    location /web1/ {
        proxy_pass http://nginx:80/;
    }

    # /web2/ へのアクセスを httpd コンテナへ転送
    location /web2/ {
        proxy_pass http://httpd:80/;
    }
}