events {
    # 必須ブロック（空でも動作しますが、一般的に最大接続数を書きます）
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        # ※以下の振り分けルールは実際の要件に合わせて変更してください
        location /web1/ {
            proxy_pass http://nginx:80/;
        }

        location /web2/ {
            proxy_pass http://httpd:80/;
        }
    }
}